=head1 NAME


pacnewrat - pacnew locator using libalpm

=head1 SYNOPSIS

Usage: I<pacnewrat>

=head1 DESCRIPTION

pacnewrat is a simple tool to find configuration files known to libalpm. 

=head1 OPERATIONS

=head1 AUTHOR

Daniel Wallace E<lt>gtmanfred@gmail.comE<gt>

Simon Gomizelj E<lt>simongmzlj@gmail.comE<gt>
